# Development environment values

postgres:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

logSvc:
  image:
    tag: dev
  replicaCount: 1
  resources:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "50m"

backend:
  image:
    tag: dev
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "20m"
    limits:
      memory: "128Mi"
      cpu: "100m"

frontend:
  image:
    tag: dev
  replicaCount: 1
  resources:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "50m"
